name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          set -e 

          echo "Stopping Service"
          systemctl --user stop ${{ secrets.SERVICE_NAME }}

          echo "Updating..."
          cd ${{ secrets.APP_DIR }}
          git pull origin master

          echo "Enabling the venv."
          source venv/bin/activate

          echo "Installing dependencies"
          pip install -r requirements.txt

          echo "Starting the service again"
          systemctl --user start ${{ secrets.SERVICE_NAME }}
          echo "Done!"
    
    - name: Release in Sentry
      uses: getsentry/action-release@v3
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        release: ${{ github.sha }}
        environment: production