name: Deploy com SSH -vvv

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Preparar chave SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Testar ligação SSH com -vvv
      run: |
        ssh -vvv -o StrictHostKeyChecking=no \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
          "echo 'Ligação SSH bem-sucedida com -vvv'"

    - name: Fazer deploy remoto
      run: |
        ssh -o StrictHostKeyChecking=no \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e

            echo "A parar o serviço..."
            systemctl --user stop ${{ secrets.SERVICE_NAME }}

            echo "A mudar para o diretório do projeto..."
            cd ${{ secrets.APP_DIR }}

            echo "A fazer git pull..."
            git pull origin master

            echo "A ativar o venv..."
            source venv/bin/activate

            echo "A instalar dependências..."
            pip install -r requirements.txt

            echo "A iniciar o serviço..."
            systemctl --user start ${{ secrets.SERVICE_NAME }}
        EOF